alias b "bundle"
alias be "bundle exec"
alias gist "gist -p"
alias git "/usr/local/bin/git"
alias gti "git"
alias history "less ~/.local/share/fish/fish_history"
alias irssi 'env TERM=screen-256color irssi'
alias ls "ls -GpF"
alias mux "tmuxinator"
alias redraw "stty sane; clear"
alias reload "redraw; source ~/.config/fish/config.fish"
alias speedtest "curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -"
alias ssh "env TERM=xterm ssh"
alias subl "/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
alias tmux "tmux -2"
alias vi "vim"
alias vim "nvim"
alias webhook-proxy "ngrok http 4567 --hostname bswinnerton.ngrok.io"
