tap nviennot/tmate
tap homebrew/dupes

install ack
install ctags
install git
install homebrew/dupes/grep
install hub
install mysql
install postgresql
install rbenv
install reattach-to-user-namespace
install ruby-build
install the_silver_searcher
install tmate
install tmux
install vim
install macvim
install wget
