model = "gpt-5.5"
model_reasoning_effort = "medium"
notify = ["/Users/brooks/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[mcp_servers.clickhouse]
command = "docker"
args = ["run", "-i", "--rm", "-e", "CLICKHOUSE_HOST", "-e", "CLICKHOUSE_PORT", "-e", "CLICKHOUSE_USER", "-e", "CLICKHOUSE_SECURE", "-e", "CLICKHOUSE_VERIFY", "-e", "CLICKHOUSE_MCP_SERVER_TRANSPORT", "-e", "CLICKHOUSE_CONNECT_TIMEOUT", "-e", "CLICKHOUSE_SEND_RECEIVE_TIMEOUT", "-e", "CLICKHOUSE_PASSWORD", "mcp/clickhouse"]
env_vars = ["CLICKHOUSE_HOST", "CLICKHOUSE_PORT", "CLICKHOUSE_USER", "CLICKHOUSE_SECURE", "CLICKHOUSE_VERIFY", "CLICKHOUSE_MCP_SERVER_TRANSPORT", "CLICKHOUSE_CONNECT_TIMEOUT", "CLICKHOUSE_SEND_RECEIVE_TIMEOUT", "CLICKHOUSE_PASSWORD"]

[mcp_servers.clickhouse.tools.list_databases]
approval_mode = "approve"

[mcp_servers.clickhouse.tools.list_tables]
approval_mode = "approve"

[mcp_servers.clickhouse.tools.run_select_query]
approval_mode = "approve"

[mcp_servers.loki]
command = "docker"
args = ["run", "-i", "--rm", "-e", "LOKI_URL", "loki-mcp-server"]
env_vars = ["LOKI_URL"]

[mcp_servers.loki.tools.loki_label_names]
approval_mode = "approve"

[mcp_servers.loki.tools.loki_query]
approval_mode = "approve"

[mcp_servers.loki.tools.loki_label_values]
approval_mode = "approve"

[mcp_servers.postgres]
command = "docker"
args = ["run", "-i", "--rm", "mcp/postgres", "postgresql://postgres@compute.corp.neptunenetworks.net:5432/neptune-networks_production"]

[mcp_servers.postgres.tools.query]
approval_mode = "approve"

[mcp_servers.prometheus]
command = "docker"
args = ["run", "-i", "--rm", "-e", "PROMETHEUS_URL", "ghcr.io/pab1it0/prometheus-mcp-server:latest"]
env_vars = ["PROMETHEUS_URL"]

[mcp_servers.sentry]
url = "https://mcp.sentry.dev/mcp"

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = ""
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/brooks/.codex"
CODEX_HOME = "/Users/brooks/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "496c7b3cb95b4bc20cff49b513150606e0da0000c92bf752206bee5a6c248423"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
BROWSER_USE_MARKETPLACE_NAME = "openai-bundled"
NODE_REPL_UNTRUSTED_ENV_ALLOWLIST = "BROWSER_USE_MARKETPLACE_NAME"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"

[projects."/Users/brooks/Sites/neptune-networks"]
trust_level = "trusted"

[projects."/Users/brooks/Sites/neptune-networks/neptune"]
trust_level = "trusted"

[projects."/Users/brooks/Sites/neptune-networks/network"]
trust_level = "trusted"

[plugins."gmail@openai-curated"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."sentry@openai-curated"]
enabled = true

[plugins."stripe@openai-curated"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[desktop]
mac-menu-bar-enabled = false

[desktop.open-in-target-preferences]
global = "zed"

[marketplaces.openai-bundled]
last_updated = "2026-05-29T04:02:24Z"
source_type = "local"
source = "/Users/brooks/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-05-29T04:02:48Z"
source_type = "local"
source = "/Users/brooks/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[features]
js_repl = false

[tui.model_availability_nux]
"gpt-5.5" = 1

[notice.model_migrations]
"gpt-5.4" = "gpt-5.5"

[apps.connector_76869538009648d5b282a4bb21c3d157.tools.github_create_pull_request]
approval_mode = "approve"
